<?php

return [
    'system_prompt' => 'You analyze PMS API documentation.'
        . ' Analyze only the provided text.'
        . ' Do not invent features that are not supported by the text.'
        . ' Use reasonable inference from labels, examples, and common abbreviations to map fields.'
        . ' If information is missing entirely, mark it as false.'
        . ' Output must be valid JSON and nothing else.',
    'pms_prompt' => 'Review the documentation and return JSON matching this schema exactly:'
        . ' {'
        . '"has_get_reservations_endpoint": boolean,'
        . '"get_reservations_endpoint": string | null,'
        . '"supports_webhooks": boolean,'
        . '"webhook_details": string | null,'
        . '"fields": {'
        . '"check_in_date": {'
        . '"available": boolean,'
        . '"source_label": string | null'
        . '},'
        . '"checkout_date": {'
        . '"available": boolean,'
        . '"source_label": string | null'
        . '},'
        . '"first_name": {'
        . '"available": boolean,'
        . '"source_label": string | null'
        . '},'
        . '"last_name": {'
        . '"available": boolean,'
        . '"source_label": string | null'
        . '},'
        . '"reservation_id": {'
        . '"available": boolean,'
        . '"source_label": string | null'
        . '},'
        . '"mobile_phone": {'
        . '"available": boolean,'
        . '"source_label": string | null'
        . '},'
        . '"email": {'
        . '"available": boolean,'
        . '"source_label": string | null'
        . '},'
        . '"reservation_status": {'
        . '"available": boolean,'
        . '"source_label": string | null,'
        . '"values": string[]'
        . '}'
        . '},'
        . '"optional_fields": string[],'
        . '"notes": string[]'
        . ' }'
        . ' Rules:'
        . ' - If a GET reservations endpoint is not explicitly documented, set has_get_reservations_endpoint to false.'
        . ' - Treat endpoint names like "get bookings", "bookings list", or "reservations list" as GET reservations endpoints.'
        . ' - If any field is not documented or inferable from labels/examples, set available to false and source_label to null.'
        . ' - If reservation status values are not listed, set values to [].'
        . ' - If has_get_reservations_endpoint is false, set get_reservations_endpoint to null.'
        . ' - If supports_webhooks is false, set webhook_details to null.'
        . ' - If available is false, source_label must be null.'
        . ' - If a field appears as a key in a response example payload, treat that as documented and use the key as source_label.'
        . ' - Match labels case-insensitively and ignore separators like spaces, underscores, and hyphens.'
        . ' - Ignore leading or trailing punctuation/symbols such as "@", "#", "*", "-", "•", ":", and "." when matching labels.'
        . ' - Labels may appear with a prefix symbol (e.g., "@telefono"). Match them without the symbol, but keep the exact original'
        . ' label (including the prefix) in source_label.'
        . ' - If you see a required field label or obvious variant directly in the documentation text, set available to true and'
        . ' use the exact label; do not default to false when a direct match exists.'
        . ' - optional_fields must list any other reservation fields documented (in response examples, field tables, or'
        . ' parameter lists) that are not part of the required fields list; use the exact labels or keys as shown.'
        . ' - Include common reservation metadata fields when documented, such as "modified_date_time", "create_date_time",'
        . ' "currency", "room_type_id", "room_type_name", "room_id", or "room_name" (use the exact label from the document).'
        . ' - If the response example contains keys not in the required fields list, include those keys in optional_fields.'
        . ' - Do not include required fields or reservation status in optional_fields.'
        . ' - If no additional reservation fields are documented, set optional_fields to [].'
        . ' - If a label is not in the explicit list but clearly refers to the same concept (abbreviation,'
        . ' language variant, or common shorthand), map it to the closest field and use the exact label as source_label.'
        . ' - When a label is ambiguous but reasonably likely to match, prefer mapping it rather than leaving it unavailable.'
        . ' - Identify labels in any language. Map common variants:'
        . ' first_name can be labeled "first name", "name", "name1", "apelido1", or "nombre";'
        . ' last_name can be labeled "last name", "name2", "apelido2", "apellido", or "surname";'
        . ' mobile_phone can be labeled "phone", "telephone", "tel", "telefono", "teléfono", "movil", "móvil", or "celular";'
        . ' check_in_date can be labeled "check-in", "check in", "checkin", "check in date", "check-in date",'
        . ' "check_in", "check_in_date", "checkin_date", "checkindate", "arrival", "arrival date", or "fecha de entrada";'
        . ' checkout_date can be labeled "check-out", "check out", "checkout", "check out date", "check-out date",'
        . ' "check_out", "check_out_date", "checkout_date", "checkoutdate", "departure", "departure date", or "fecha de salida";'
        . ' reservation_id can be labeled "reservation id", "reservation number", "booking id", "booking number",'
        . ' "id de reserva", or "numero de reserva";'
        . ' email can be labeled "email", "e-mail", "correo", "correo electronico", "correo electrónico", or "mail";'
        . ' reservation_status can be labeled "status", "reservation status", "reservation_status", "state", "estado", or "situacao";'
        . ' - For source_label, return the exact label text from the documentation.'
        . ' Respond with JSON only.',
    'booking_engine_prompt' => 'Review the documentation and return JSON matching this schema exactly:'
        . ' {'
        . '"has_get_availability_endpoint": boolean,'
        . '"get_availability_endpoint": string | null,'
        . '"availability_fields": {'
        . '"room_description": {'
        . '"available": boolean,'
        . '"source_label": string | null'
        . '},'
        . '"room_image": {'
        . '"available": boolean,'
        . '"source_label": string | null'
        . '},'
        . '"price": {'
        . '"available": boolean,'
        . '"source_label": string | null'
        . '},'
        . '"currency": {'
        . '"available": boolean,'
        . '"source_label": string | null'
        . '}'
        . '},'
        . '"optional_fields": string[],'
        . '"notes": string[]'
        . ' }'
        . ' Rules:'
        . ' - If a GET availability endpoint is not explicitly documented, set has_get_availability_endpoint to false.'
        . ' - If any field is not documented or inferable from labels/examples, set available to false and source_label to null.'
        . ' - If has_get_availability_endpoint is false, set get_availability_endpoint to null.'
        . ' - If available is false, source_label must be null.'
        . ' - If a field appears as a key in a response example payload, treat that as documented and use the key as source_label.'
        . ' - Match labels case-insensitively and ignore separators like spaces, underscores, and hyphens.'
        . ' - Ignore leading or trailing punctuation/symbols such as "@", "#", "*", "-", "•", ":", and "." when matching labels.'
        . ' - Labels may appear with a prefix symbol (e.g., "@room_description"). Match them without the symbol, but keep the exact original'
        . ' label (including the prefix) in source_label.'
        . ' - If you see a required field label or obvious variant directly in the documentation text, set available to true and'
        . ' use the exact label; do not default to false when a direct match exists.'
        . ' - optional_fields must list any other availability fields documented (in response examples, field tables, or'
        . ' parameter lists) that are not part of the required fields list; use the exact labels or keys as shown.'
        . ' - Do not include required fields in optional_fields.'
        . ' - If no additional availability fields are documented, set optional_fields to [].'
        . ' - If a label is not in the explicit list but clearly refers to the same concept (abbreviation,'
        . ' language variant, or common shorthand), map it to the closest field and use the exact label as source_label.'
        . ' - When a label is ambiguous but reasonably likely to match, prefer mapping it rather than leaving it unavailable.'
        . ' - Identify labels in any language. Map common variants:'
        . ' room_description can be labeled "room description", "room name", "room", "room_name", "room_type_name",'
        . ' "room_desc", "description", or "descripcion";'
        . ' room_image can be labeled "room image", "room_image", "image", "image_url", "photo", "room_photo", or "foto";'
        . ' price can be labeled "price", "rate", "amount", "room_price", "price_per_night", or "total_price";'
        . ' currency can be labeled "currency", "currency_code", "currency_iso", or "iso_currency";'
        . ' - For source_label, return the exact label text from the documentation.'
        . ' Respond with JSON only.',
    'example_prompt' => 'Review the documentation and return JSON matching this schema exactly:'
        . ' {'
        . '"get_reservations_example": {'
        . '"format": string | null,'
        . '"payload": string | null'
        . '}'
        . ' }'
        . ' Rules:'
        . ' - If a GET reservations response example is documented, include a successful response example in get_reservations_example.'
        . ' - If multiple examples are documented, prefer the success response and ignore error examples.'
        . ' - get_reservations_example.format must be a lowercase format label when payload is provided.'
        . ' - Use "json" or "xml" when the example is clearly JSON or XML; otherwise use the documented format name (e.g., "yaml", "text").'
        . ' - If no example is documented, set get_reservations_example.format and payload to null.'
        . ' - Return the payload exactly as shown (no edits) when possible.'
        . ' Respond with JSON only.',
];
